### ISSUE TITLE
self.data.url() returns a path with 'NaN' at the beginning

### ISSUE THREAD

**Issue by customcommander** [mozilla/jpm#311]
I'm running Firefox 39 (on a MBP) and `jpm`.

When I type this in in the developer console while I'm working on my extension:

```javascript
var self = require('sdk/self');
self.data.url('foo/bar');
```

Output is:

```
NaN/data/foo/bar
```

Which doesn't look right.

**Comment by anaran** [comment]
What do you get for

jpm -V

**Comment by customcommander** [comment]
1.0.0

**Comment by ZER0** [comment]
> When I type this in in the developer console while I'm working on my extension:

Not sure what you mean with "developer console", could you please elaborate a bit?
Notice that `data.url` works properly only for add-on, so, the module `sdk/self` needs to be loaded inside an add-on execution, not dynamically in scratchpad on from browser console, for example; unless you simulate perfectly the add-on environment when you create a custom loader.

**Comment by customcommander** [comment]
Yep that's a bit confusing sorry. What I meant is the console you get when you do:

```
cd /path/to/my/extension
jpm run --debug
````

Which I think is some sort of privileged console that has access to the add-on environment. (So `require('sdk/self');` does load the module.)

Anyway both that console and my add-on code report the same `NaN`at the beginning of the string.

**Comment by ZER0** [comment]
As I thought, the `require` you got from the browser console is not the `require` of your add-on, but one used for loading the `bootstrap`; so it doesn't have any of the information that the add-on's `require` has. It's like create a custom empty loader, as mentioned before, and executing in scratchpad.

I can understand that is surprising, and a bit misleading, but it seems a consequence of the new add-on structure that we have with jpm instead of cfx; you're able to debug the code using the debugger, but the console is not running in the scope of the add-on's main module.

From your add-on code – e.g. `index.js` in your add-on folder – the value should be correct, due the fact that the `require` is the one of the add-on, with the proper options loaded.

**Comment by customcommander** [comment]
It looks like you're correct. The console (as given by `jpm run --debug`) gives a `NaN` for `self.data.url('foo/bar')` while the same code returns a correct path if executed within the add-on straightaway.

It is misleading indeed.

Closing.
